### ISSUE TITLE
Add support for private networks

### ISSUE THREAD

**Issue by vpulim** [ethereumjs/ethereumjs-common#22]
In order to support private networks, we should allow an instance of Common to be created from a [chain spec](https://github.com/ethereum/wiki/wiki/Ethereum-Chain-Spec-Format#example) and/or a geth [genesis file](https://arvanaghi.com/blog/explaining-the-genesis-block-in-ethereum/). Any of the following would be user-friendly ways to construct a Common instance from a spec file:

```
const common = Common.fromSpec('./genesis.json')
```
```
const common = Common.fromJson('./genesis.json')
```
```
const spec = require('./genesis.json')
const common = new Common(spec) // detect first argument is an Object instead of string
```

We could also consider migrating the json definition files in the ``chains/`` folder to the chain spec format for consistency and future-proofing.

**Comment by holgerd77** [comment]
I've some reservations towards the chain spec format, that's why I somewhat put that aside.

These are mainly:
- Integrating the accounts makes the file very large especially for mainnet, which puts an unnecessary burden on loading for many use cases not needing the accounts
- Including the hardforks like in the genesis file definitions makes things unnecessarily static, e.g. if there is another HF on the horizon and one would want to add some draft params, then one would have to wait for the official genesis files to update. This also doesn't fit (at all) to our current file structure with the parameter override mechanism on new HFs
- I also don't think that the ever-changing bootstrap nodes belong into the chain spec and is better kept separate. This also prevents (somewhat theoretical atm) to provide a hash to prove the integrity of the static genesis parameters

So: there would be definitely some more discussion necessary if we want to move in this direction. Atm I actually wouldn't want to set a priority here. Maybe some middle ground would be to adopt naming and un-problematic structure as much as possible but e.g. leave accounts and bootstrap nodes separate (people could just copy-and-paste to separate files, which should be acceptable).

There is actually some ongoing discussion atm on [Gitter](https://gitter.im/ethereum/crossclient_standards) about crossclient standards on genesis definition, but I somewhat dropped here since I wasn't so satisfied with the running discussion.

**Comment by vpulim** [comment]
Yes, no urgency to adopt the full chain spec format. However, I do need to be able to load custom genesis settings into a Common instance in order to connect to a private test net I've set up for ethereumjs client debugging/testing. A simple short-term solution could be to modify Common.setChain() to also accept an external chainParams object. This way, the gensis.json parsing can be done in the client and the resulting params object can be passed on to setChain.
